---
version: "3"

services:
  flask-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: ssinghal37/midterm:1.0
    container_name: midterm-iss-app
    ports:
      - "5000:5000"
...
